INSERT INTO user (email, password_hash, role)
VALUES ('demo@localhost', '$2a$10$ebyC4Z5WtCXXc.HGDc1Yoe6CLFzcntFmfse6/pTj7CeDY5I05w16C', 'ADMIN');

INSERT INTO activity (code, mets, heading, description) VALUES (01009, 8.5, 'bicycling', 'bicycling, BMX or mountain');
INSERT INTO activity (code, mets, heading, description) VALUES (01010, 4.0, 'bicycling', 'bicycling, <10 mph, leisure, to work or for pleasure (Taylor Code 115');
INSERT INTO activity (code, mets, heading, description) VALUES (01015, 8.0, 'bicycling', 'bicycling, general');
INSERT INTO activity (code, mets, heading, description) VALUES (01020, 6.0, 'bicycling', 'bicycling, 10-11.9 mph, leisure, slow, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (01030, 8.0, 'bicycling', 'bicycling, 12-13.9 mph, leisure, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (01040, 10.0, 'bicycling', 'bicycling, 14-15.9 mph, racing or leisure, fast, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (01050, 12.0, 'bicycling', 'bicycling, 16-19 mph, racing/not drafting or >19 mph drafting, very fast, racing genera');
INSERT INTO activity (code, mets, heading, description) VALUES (01060, 16.0, 'bicycling', 'bicycling, >20 mph, racing, not drafting');
INSERT INTO activity (code, mets, heading, description) VALUES (01070, 5.0, 'bicycling', 'unicycling');
INSERT INTO activity (code, mets, heading, description) VALUES (02010, 7.0, 'conditioning exercise', 'bicycling, stationary, general');
INSERT INTO activity (code, mets, heading, description) VALUES (02011, 3.0, 'conditioning exercise', 'bicycling, stationary, 50 watts, very light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02012, 5.5, 'conditioning exercise', 'bicycling, stationary, 100 watts, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02013, 7.0, 'conditioning exercise', 'bicycling, stationary, 150 watts, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02014, 10.5, 'conditioning exercise', 'bicycling, stationary, 200 watts, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02015, 12.5, 'conditioning exercise', 'bicycling, stationary, 250 watts, very vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02020, 8.0, 'conditioning exercise', 'calisthenics (e.g. pushups, situps, pullups, jumping jacks), heavy, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02030, 3.5, 'conditioning exercise', 'calisthenics, home exercise, light or moderate effort, general (example: back exercises), going up & down from floor (Taylor Code 150');
INSERT INTO activity (code, mets, heading, description) VALUES (02040, 8.0, 'conditioning exercise', 'circuit training, including some aerobic movement with minimal rest, general');
INSERT INTO activity (code, mets, heading, description) VALUES (02050, 6.0, 'conditioning exercise', 'weight lifting (free weight, nautilus or universal-type), power lifting or body building, vigorous effort (Taylor Code 210');
INSERT INTO activity (code, mets, heading, description) VALUES (02060, 5.5, 'conditioning exercise', 'health club exercise, general (Taylor Code 160');
INSERT INTO activity (code, mets, heading, description) VALUES (02065, 9.0, 'conditioning exercise', 'stair-treadmill ergometer, general');
INSERT INTO activity (code, mets, heading, description) VALUES (02070, 7.0, 'conditioning exercise', 'rowing, stationary ergometer, genera');
INSERT INTO activity (code, mets, heading, description) VALUES (02071, 3.5, 'conditioning exercise', 'rowing, stationary, 50 watts, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02072, 7.0, 'conditioning exercise', 'rowing, stationary, 100 watts, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02073, 8.5, 'conditioning exercise', 'rowing, stationary, 150 watts, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02074, 12.0, 'conditioning exercise', 'rowing, stationary, 200 watts, very vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (02080, 7.0, 'conditioning exercise', 'ski machine, general');
INSERT INTO activity (code, mets, heading, description) VALUES (02090, 6.0, 'conditioning exercise', 'slimnastics, jazzercise');
INSERT INTO activity (code, mets, heading, description) VALUES (02100, 2.5, 'conditioning exercise', 'stretching, hatha yoga');
INSERT INTO activity (code, mets, heading, description) VALUES (02101, 2.5, 'conditioning exercise', 'mild stretching');
INSERT INTO activity (code, mets, heading, description) VALUES (02110, 6.0, 'conditioning exercise', 'teaching aerobic exercise class');
INSERT INTO activity (code, mets, heading, description) VALUES (02120, 4.0, 'conditioning exercise', 'water aerobics, water calisthenics');
INSERT INTO activity (code, mets, heading, description) VALUES (02130, 3.0, 'conditioning exercise', 'weight lifting (free, nautilus or universal-type), light or moderate effort, light workout, genera');
INSERT INTO activity (code, mets, heading, description) VALUES (02135, 1.0, 'conditioning exercise', 'whirlpool, sitting');
INSERT INTO activity (code, mets, heading, description) VALUES (03010, 4.8, 'dancing', 'ballet or modern, twist, jazz, tap, jitterbug');
INSERT INTO activity (code, mets, heading, description) VALUES (03015, 6.5, 'dancing', 'aerobic, general');
INSERT INTO activity (code, mets, heading, description) VALUES (03016, 8.5, 'dancing', 'aerobic, step, with 6 – 8 inch step');
INSERT INTO activity (code, mets, heading, description) VALUES (03017, 10.0, 'dancing', 'aerobic, step, with 10 – 12 inch step');
INSERT INTO activity (code, mets, heading, description) VALUES (03020, 5.0, 'dancing', 'aerobic, low impact');
INSERT INTO activity (code, mets, heading, description) VALUES (03021, 7.0, 'dancing', 'aerobic, high impact');
INSERT INTO activity (code, mets, heading, description) VALUES (03025, 4.5, 'dancing', 'general, Greek, Middle Eastern, hula, flamenco, belly, and swing dancing');
INSERT INTO activity (code, mets, heading, description) VALUES (03030, 5.5, 'dancing', 'ballroom, dancing fast (Taylor Code 125)');
INSERT INTO activity (code, mets, heading, description) VALUES (03031, 4.5, 'dancing', 'ballroom, fast (disco, folk, square), line dancing, Irish step dancing, polka, contra, country');
INSERT INTO activity (code, mets, heading, description) VALUES (03040, 3.0, 'dancing', 'ballroom, slow (e.g. waltz, foxtrot, slow dancing),samba, tango, 19th C, mambo, chacha');
INSERT INTO activity (code, mets, heading, description) VALUES (03050, 5.5, 'dancing', 'Anishinaabe Jingle Dancing or other traditional American Indian dancing');
INSERT INTO activity (code, mets, heading, description) VALUES (04001, 3.0, 'fishing and hunting', 'fishing, general');
INSERT INTO activity (code, mets, heading, description) VALUES (04010, 4.0, 'fishing and hunting', 'digging worms, with shovel');
INSERT INTO activity (code, mets, heading, description) VALUES (04020, 4.0, 'fishing and hunting', 'fishing from river bank and walking');
INSERT INTO activity (code, mets, heading, description) VALUES (04030, 2.5, 'fishing and hunting', 'fishing from boat, sitting');
INSERT INTO activity (code, mets, heading, description) VALUES (04040, 3.5, 'fishing and hunting', 'fishing from river bank, standing (Taylor Code 660)');
INSERT INTO activity (code, mets, heading, description) VALUES (04050, 6.0, 'fishing and hunting', 'fishing in stream, in waders (Taylor Code 670)');
INSERT INTO activity (code, mets, heading, description) VALUES (04060, 2.0, 'fishing and hunting', 'fishing, ice, sitting');
INSERT INTO activity (code, mets, heading, description) VALUES (04070, 2.5, 'fishing and hunting', 'hunting, bow and arrow or crossbow');
INSERT INTO activity (code, mets, heading, description) VALUES (04080, 6.0, 'fishing and hunting', 'hunting, deer, elk, large game (Taylor Code 170)');
INSERT INTO activity (code, mets, heading, description) VALUES (04090, 2.5, 'fishing and hunting', 'hunting, duck, wading');
INSERT INTO activity (code, mets, heading, description) VALUES (04100, 5.0, 'fishing and hunting', 'hunting, general');
INSERT INTO activity (code, mets, heading, description) VALUES (04110, 6.0, 'fishing and hunting', 'hunting, pheasants or grouse (Taylor Code 680');
INSERT INTO activity (code, mets, heading, description) VALUES (04120, 5.0, 'fishing and hunting', 'hunting, rabbit, squirrel, prairie chick, raccoon, small game (Taylor Code 690)');
INSERT INTO activity (code, mets, heading, description) VALUES (04130, 2.5, 'fishing and hunting', 'pistol shooting or trap shooting, standing');
INSERT INTO activity (code, mets, heading, description) VALUES (05010, 3.3, 'home activities', 'carpet sweeping, sweeping floors');
INSERT INTO activity (code, mets, heading, description) VALUES (05020, 3.0, 'home activities', 'cleaning, heavy or major (e.g. wash car, wash windows, clean garage), vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05021, 3.5, 'home activities', 'mopping');
INSERT INTO activity (code, mets, heading, description) VALUES (05025, 2.5, 'home activities', 'multiple household tasks all at once, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05026, 3.5, 'home activities', 'multiple household tasks all at once, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05027, 4.0, 'home activities', 'multiple household tasks all at once, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05030, 3.0, 'home activities', 'cleaning, house or cabin, genera');
INSERT INTO activity (code, mets, heading, description) VALUES (05040, 2.5, 'home activities', 'cleaning, light (dusting, straightening up, changing linen, carrying out trash');
INSERT INTO activity (code, mets, heading, description) VALUES (05041, 2.3, 'home activities', 'wash dishes - standing or in general (not broken into stand/walk components');
INSERT INTO activity (code, mets, heading, description) VALUES (05042, 2.5, 'home activities', 'wash dishes; clearing dishes from table – walking');
INSERT INTO activity (code, mets, heading, description) VALUES (05043, 3.5, 'home activities', 'vacuuming');
INSERT INTO activity (code, mets, heading, description) VALUES (05045, 6.0, 'home activities', 'butchering animals');
INSERT INTO activity (code, mets, heading, description) VALUES (05050, 2.0, 'home activities', 'cooking or food preparation - standing or sitting or in general (not broken into stand/walk components), manual appliance');
INSERT INTO activity (code, mets, heading, description) VALUES (05051, 2.5, 'home activities', 'serving food, setting table - implied walking or standing');
INSERT INTO activity (code, mets, heading, description) VALUES (05052, 2.5, 'home activities', 'cooking or food preparation - walking');
INSERT INTO activity (code, mets, heading, description) VALUES (05053, 2.5, 'home activities', 'feeding animals');
INSERT INTO activity (code, mets, heading, description) VALUES (05055, 2.5, 'home activities', 'putting away groceries (e.g. carrying groceries, shopping without a grocery cart), carrying packages');
INSERT INTO activity (code, mets, heading, description) VALUES (05056, 7.5, 'home activities', 'carrying groceries upstairs');
INSERT INTO activity (code, mets, heading, description) VALUES (05057, 3.0, 'home activities', 'cooking Indian bread on an outside stove');
INSERT INTO activity (code, mets, heading, description) VALUES (05060, 2.3, 'home activities', 'food shopping with or without a grocery cart, standing or walking');
INSERT INTO activity (code, mets, heading, description) VALUES (05065, 2.3, 'home activities', 'non-food shopping, standing or walking');
INSERT INTO activity (code, mets, heading, description) VALUES (05066, 0.0 , 'home activities', 'walking shopping (non-grocery shopping)');
INSERT INTO activity (code, mets, heading, description) VALUES (05070, 2.3, 'home activities', 'ironing');
INSERT INTO activity (code, mets, heading, description) VALUES (05080, 1.5, 'home activities', 'sitting - knitting, sewing, lt. wrapping (presents)');
INSERT INTO activity (code, mets, heading, description) VALUES (05090, 2.0, 'home activities', 'implied standing - laundry, fold or hang clothes, put clothes in washer or dryer, packing suitcase');
INSERT INTO activity (code, mets, heading, description) VALUES (05095, 2.3, 'home activities', 'implied walking - putting away clothes, gathering clothes to pack, putting away laundry');
INSERT INTO activity (code, mets, heading, description) VALUES (05100, 2.0, 'home activities', 'making bed');
INSERT INTO activity (code, mets, heading, description) VALUES (05110, 5.0, 'home activities', 'maple syruping/sugar bushing (including carrying buckets, carrying wood)');
INSERT INTO activity (code, mets, heading, description) VALUES (05120, 6.0, 'home activities', 'moving furniture, household items,carrying boxes');
INSERT INTO activity (code, mets, heading, description) VALUES (05130, 3.8, 'home activities', 'scrubbing floors, on hands and knees, scrubbing bathroom, bathtub');
INSERT INTO activity (code, mets, heading, description) VALUES (05140, 4.0, 'home activities', 'sweeping garage, sidewalk or outside of house');
INSERT INTO activity (code, mets, heading, description) VALUES (05141, 0.0 , 'home activities', 'moving household items, carrying boxes');
INSERT INTO activity (code, mets, heading, description) VALUES (05146, 3.5, 'home activities', 'standing - packing/unpacking boxes, occasional lifting of household items light - moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05147, 3.0, 'home activities', 'implied walking - putting away household items - moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05148, 2.5, 'home activities', 'watering plants');
INSERT INTO activity (code, mets, heading, description) VALUES (05149, 2.5, 'home activities', 'building a fire inside');
INSERT INTO activity (code, mets, heading, description) VALUES (05150, 9.0, 'home activities', 'moving household items upstairs, carrying boxes or furniture');
INSERT INTO activity (code, mets, heading, description) VALUES (05160, 2.0, 'home activities', 'standing - light (pump gas, change light bulb, etc.)');
INSERT INTO activity (code, mets, heading, description) VALUES (05165, 3.0, 'home activities', 'walking - light, non-cleaning (readying to leave, shut/lock doors, close windows, etc.');
INSERT INTO activity (code, mets, heading, description) VALUES (05170, 2.5, 'home activities', 'sitting - playing with child(ren) – light, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05171, 2.8, 'home activities', 'standing - playing with child(ren) – light, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05175, 4.0, 'home activities', 'walk/run - playing with child(ren) – moderate, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05180, 5.0, 'home activities', 'walk/run - playing with child(ren) – vigorous, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05181, 3.0, 'home activities', 'carrying small children');
INSERT INTO activity (code, mets, heading, description) VALUES (05185, 2.5, 'home activities', 'child care: sitting/kneeling - dressing, bathing, grooming, feeding, occasional lifting of child-light effort, genera');
INSERT INTO activity (code, mets, heading, description) VALUES (05186, 3.0, 'home activities', 'child care: standing - dressing, bathing, grooming, feeding, occasional lifting of child-light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (05187, 4.0, 'home activities', 'elder care, disabled adult, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05188, 1.5, 'home activities', 'reclining with baby');
INSERT INTO activity (code, mets, heading, description) VALUES (05190, 2.5, 'home activities', 'sit, playing with animals, light, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05191, 2.8, 'home activities', 'stand, playing with animals, light, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05192, 2.8, 'home activities', 'walk/run, playing with animals, light, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05193, 4.0, 'home activities', 'walk/run, playing with animals, moderate, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05194, 5.0, 'home activities', 'walk/run, playing with animals, vigorous, only active periods');
INSERT INTO activity (code, mets, heading, description) VALUES (05195, 3.5, 'home activities', 'standing - bathing dog');
INSERT INTO activity (code, mets, heading, description) VALUES (06010, 3.0, 'home repair', 'airplane repair');
INSERT INTO activity (code, mets, heading, description) VALUES (06020, 4.0, 'home repair', 'automobile body work');
INSERT INTO activity (code, mets, heading, description) VALUES (06030, 3.0, 'home repair', 'automobile repair');
INSERT INTO activity (code, mets, heading, description) VALUES (06040, 3.0, 'home repair', 'carpentry, general, workshop (Taylor Code 620)');
INSERT INTO activity (code, mets, heading, description) VALUES (06050, 6.0, 'home repair', 'carpentry, outside house, installing rain gutters,building a fence, (Taylor Code 640)');
INSERT INTO activity (code, mets, heading, description) VALUES (06060, 4.5, 'home repair', 'carpentry, finishing or refinishing cabinets or furniture');
INSERT INTO activity (code, mets, heading, description) VALUES (06070, 7.5, 'home repair', 'carpentry, sawing hardwood');
INSERT INTO activity (code, mets, heading, description) VALUES (06080, 5.0, 'home repair', 'caulking, chinking log cabin');
INSERT INTO activity (code, mets, heading, description) VALUES (06090, 4.5, 'home repair', 'caulking, except log cabin');
INSERT INTO activity (code, mets, heading, description) VALUES (06100, 5.0, 'home repair', 'cleaning gutters');
INSERT INTO activity (code, mets, heading, description) VALUES (06110, 5.0, 'home repair', 'excavating garage');
INSERT INTO activity (code, mets, heading, description) VALUES (06120, 5.0, 'home repair', 'hanging storm windows');
INSERT INTO activity (code, mets, heading, description) VALUES (06130, 4.5, 'home repair', 'laying or removing carpet');
INSERT INTO activity (code, mets, heading, description) VALUES (06140, 4.5, 'home repair', 'laying tile or linoleum, repairing appliances');
INSERT INTO activity (code, mets, heading, description) VALUES (06150, 5.0, 'home repair', 'painting, outside home (Taylor Code 650)');
INSERT INTO activity (code, mets, heading, description) VALUES (06160, 3.0, 'home repair', 'painting, papering, plastering, scraping, inside house, hanging sheet rock, remodeling');
INSERT INTO activity (code, mets, heading, description) VALUES (06165, 4.5, 'home repair', 'painting, (Taylor Code 630)');
INSERT INTO activity (code, mets, heading, description) VALUES (06170, 3.0, 'home repair', 'put on and removal of tarp - sailboat');
INSERT INTO activity (code, mets, heading, description) VALUES (06180, 6.0, 'home repair', 'roofing');
INSERT INTO activity (code, mets, heading, description) VALUES (06190, 4.5, 'home repair', 'sanding floors with a power sander');
INSERT INTO activity (code, mets, heading, description) VALUES (06200, 4.5, 'home repair', 'scraping and painting sailboat or powerboat');
INSERT INTO activity (code, mets, heading, description) VALUES (06210, 5.0, 'home repair', 'spreading dirt with a shovel');
INSERT INTO activity (code, mets, heading, description) VALUES (06220, 4.5, 'home repair', 'washing and waxing hull of sailboat, car, powerboat, airplane');
INSERT INTO activity (code, mets, heading, description) VALUES (06230, 4.5, 'home repair', 'washing fence, painting fence');
INSERT INTO activity (code, mets, heading, description) VALUES (06240, 3.0, 'home repair', 'wiring, plumbing');
INSERT INTO activity (code, mets, heading, description) VALUES (07010, 1.0, 'inactivity quiet', 'lying quietly, watching television');
INSERT INTO activity (code, mets, heading, description) VALUES (07011, 1.0, 'inactivity quiet', 'lying quietly, doing nothing, lying in bed awake, listening to music (not talking or reading)');
INSERT INTO activity (code, mets, heading, description) VALUES (07020, 1.0, 'inactivity quiet', 'sitting quietly and watching television');
INSERT INTO activity (code, mets, heading, description) VALUES (07021, 1.0, 'inactivity quiet', 'sitting quietly, sitting smoking, listening to music (not talking or reading), watching a movie in a theater');
INSERT INTO activity (code, mets, heading, description) VALUES (07030, 0.9, 'inactivity quiet', 'sleeping');
INSERT INTO activity (code, mets, heading, description) VALUES (07040, 1.2, 'inactivity quiet', 'standing quietly (standing in a line)');
INSERT INTO activity (code, mets, heading, description) VALUES (07050, 1.0, 'inactivity light', 'reclining - writing');
INSERT INTO activity (code, mets, heading, description) VALUES (07060, 1.0, 'inactivity light', 'reclining - talking or talking on phone');
INSERT INTO activity (code, mets, heading, description) VALUES (07070, 1.0, 'inactivity light', 'reclining - reading');
INSERT INTO activity (code, mets, heading, description) VALUES (07075, 1.0, 'inactivity light', 'meditating');
INSERT INTO activity (code, mets, heading, description) VALUES (08010, 5.0, 'lawn and garden', 'carrying, loading or stacking wood, loading/unloading or carrying lumber');
INSERT INTO activity (code, mets, heading, description) VALUES (08020, 6.0, 'lawn and garden', 'chopping wood, splitting logs');
INSERT INTO activity (code, mets, heading, description) VALUES (08030, 5.0, 'lawn and garden', 'clearing land, hauling branches, wheelbarrow chores');
INSERT INTO activity (code, mets, heading, description) VALUES (08040, 5.0, 'lawn and garden', 'digging sandbox');
INSERT INTO activity (code, mets, heading, description) VALUES (08050, 5.0, 'lawn and garden', 'digging, spading, filling garden, composting, (Taylor Code 590)');
INSERT INTO activity (code, mets, heading, description) VALUES (08060, 6.0, 'lawn and garden', 'gardening with heavy power tools, tilling a garden, chain saw');
INSERT INTO activity (code, mets, heading, description) VALUES (08080, 5.0, 'lawn and garden', 'laying crushed rock');
INSERT INTO activity (code, mets, heading, description) VALUES (08090, 5.0, 'lawn and garden', 'laying sod');
INSERT INTO activity (code, mets, heading, description) VALUES (08095, 5.5, 'lawn and garden', 'mowing lawn, general');
INSERT INTO activity (code, mets, heading, description) VALUES (08100, 2.5, 'lawn and garden', 'mowing lawn, riding mower (Taylor Code 550)');
INSERT INTO activity (code, mets, heading, description) VALUES (08110, 6.0, 'lawn and garden', 'mowing lawn, walk, hand mower (Taylor Code 570)');
INSERT INTO activity (code, mets, heading, description) VALUES (08120, 5.5, 'lawn and garden', 'mowing lawn, walk, power mower');
INSERT INTO activity (code, mets, heading, description) VALUES (08125, 4.5, 'lawn and garden', 'mowing lawn, power mower (Taylor Code 590)');
INSERT INTO activity (code, mets, heading, description) VALUES (08130, 4.5, 'lawn and garden', 'operating snow blower, walking');
INSERT INTO activity (code, mets, heading, description) VALUES (08140, 4.5, 'lawn and garden', 'planting seedlings, shrubs');
INSERT INTO activity (code, mets, heading, description) VALUES (08150, 4.5, 'lawn and garden', 'planting trees');
INSERT INTO activity (code, mets, heading, description) VALUES (08160, 4.3, 'lawn and garden', 'raking lawn');
INSERT INTO activity (code, mets, heading, description) VALUES (08165, 4.0, 'lawn and garden', 'raking lawn (Taylor Code 600)');
INSERT INTO activity (code, mets, heading, description) VALUES (08170, 4.0, 'lawn and garden', 'raking roof with snow rake');
INSERT INTO activity (code, mets, heading, description) VALUES (08180, 3.0, 'lawn and garden', 'riding snow blower');
INSERT INTO activity (code, mets, heading, description) VALUES (08190, 4.0, 'lawn and garden', 'sacking grass, leaves');
INSERT INTO activity (code, mets, heading, description) VALUES (08200, 6.0, 'lawn and garden', 'shoveling snow, by hand (Taylor Code 610)');
INSERT INTO activity (code, mets, heading, description) VALUES (08210, 4.5, 'lawn and garden', 'trimming shrubs or trees, manual cutter');
INSERT INTO activity (code, mets, heading, description) VALUES (08215, 3.5, 'lawn and garden', 'trimming shrubs or trees, power cutter, using leaf blower, edger');
INSERT INTO activity (code, mets, heading, description) VALUES (08220, 2.5, 'lawn and garden', 'walking, applying fertilizer or seeding a lawn');
INSERT INTO activity (code, mets, heading, description) VALUES (08230, 1.5, 'lawn and garden', 'watering lawn or garden, standing or walking');
INSERT INTO activity (code, mets, heading, description) VALUES (08240, 4.5, 'lawn and garden', 'weeding, cultivating garden (Taylor Code 580)');
INSERT INTO activity (code, mets, heading, description) VALUES (08245, 4.0, 'lawn and garden', 'gardening, general');
INSERT INTO activity (code, mets, heading, description) VALUES (08246, 3.0, 'lawn and garden', 'picking fruit off trees, picking fruits/vegetables, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (08250, 3.0, 'lawn and garden', 'implied walking/standing - picking up yard, light, picking flowers or vegetables');
INSERT INTO activity (code, mets, heading, description) VALUES (08251, 3.0, 'lawn and garden', 'walking, gathering gardening tools');
INSERT INTO activity (code, mets, heading, description) VALUES (09010, 1.5, 'miscellaneous', 'sitting - card playing, playing board games');
INSERT INTO activity (code, mets, heading, description) VALUES (09020, 2.3, 'miscellaneous', 'standing - drawing (writing), casino gambling, duplicating machine');
INSERT INTO activity (code, mets, heading, description) VALUES (09030, 1.3, 'miscellaneous', 'sitting - reading, book, newspaper, etc.');
INSERT INTO activity (code, mets, heading, description) VALUES (09040, 1.8, 'miscellaneous', 'sitting - writing, desk work, typing');
INSERT INTO activity (code, mets, heading, description) VALUES (09050, 1.8, 'miscellaneous', 'standing - talking or talking on the phone');
INSERT INTO activity (code, mets, heading, description) VALUES (09055, 1.5, 'miscellaneous', 'sitting - talking or talking on the phone');
INSERT INTO activity (code, mets, heading, description) VALUES (09060, 1.8, 'miscellaneous', 'sitting - studying, general, including reading and/or writing');
INSERT INTO activity (code, mets, heading, description) VALUES (09065, 1.8, 'miscellaneous', 'sitting - in class, general, including note-taking or class discussion');
INSERT INTO activity (code, mets, heading, description) VALUES (09070, 1.8, 'miscellaneous', 'standing - reading');
INSERT INTO activity (code, mets, heading, description) VALUES (09071, 2.0, 'miscellaneous', 'standing - miscellaneous');
INSERT INTO activity (code, mets, heading, description) VALUES (09075, 1.5, 'miscellaneous', 'sitting - arts and crafts, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (09080, 2.0, 'miscellaneous', 'sitting - arts and crafts, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (09085, 1.8, 'miscellaneous', 'standing - arts and crafts, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (09090, 3.0, 'miscellaneous', 'standing - arts and crafts, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (09095, 3.5, 'miscellaneous', 'standing - arts and crafts, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (09100, 1.5, 'miscellaneous', 'retreat/family reunion activities involving sitting, relaxing, talking, eating');
INSERT INTO activity (code, mets, heading, description) VALUES (09105, 2.0, 'miscellaneous', 'touring/traveling/vacation involving walking and riding');
INSERT INTO activity (code, mets, heading, description) VALUES (09110, 2.5, 'miscellaneous', 'camping involving standing, walking, sitting, light-to-moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (09115, 1.5, 'miscellaneous', 'sitting at a sporting event, spectator');
INSERT INTO activity (code, mets, heading, description) VALUES (10010, 1.8, 'music playing', 'accordion');
INSERT INTO activity (code, mets, heading, description) VALUES (10020, 2.0, 'music playing', 'cello');
INSERT INTO activity (code, mets, heading, description) VALUES (10030, 2.5, 'music playing', 'conducting');
INSERT INTO activity (code, mets, heading, description) VALUES (10040, 4.0, 'music playing', 'drums');
INSERT INTO activity (code, mets, heading, description) VALUES (10050, 2.0, 'music playing', 'flute (sitting)');
INSERT INTO activity (code, mets, heading, description) VALUES (10060, 2.0, 'music playing', 'horn');
INSERT INTO activity (code, mets, heading, description) VALUES (10070, 2.5, 'music playing', 'piano or organ');
INSERT INTO activity (code, mets, heading, description) VALUES (10080, 3.5, 'music playing', 'trombone');
INSERT INTO activity (code, mets, heading, description) VALUES (10090, 2.5, 'music playing', 'trumpet');
INSERT INTO activity (code, mets, heading, description) VALUES (10100, 2.5, 'music playing', 'violin');
INSERT INTO activity (code, mets, heading, description) VALUES (10110, 2.0, 'music playing', 'woodwind');
INSERT INTO activity (code, mets, heading, description) VALUES (10120, 2.0, 'music playing', 'guitar, classical, folk (sitting)');
INSERT INTO activity (code, mets, heading, description) VALUES (10125, 3.0, 'music playing', 'guitar, rock and roll band (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (10130, 4.0, 'music playing', 'marching band, playing an instrument, baton twirling (walking)');
INSERT INTO activity (code, mets, heading, description) VALUES (10135, 3.5, 'music playing', 'marching band, drum major (walking)');
INSERT INTO activity (code, mets, heading, description) VALUES (11010, 4.0, 'occupation', 'bakery, general, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11015, 2.5, 'occupation', 'bakery, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11020, 2.3, 'occupation', 'bookbinding');
INSERT INTO activity (code, mets, heading, description) VALUES (11030, 6.0, 'occupation', 'building road (including hauling debris, driving heavy machinery)');
INSERT INTO activity (code, mets, heading, description) VALUES (11035, 2.0, 'occupation', 'building road, directing traffic (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11040, 3.5, 'occupation', 'carpentry, general');
INSERT INTO activity (code, mets, heading, description) VALUES (11050, 8.0, 'occupation', 'carrying heavy loads, such as bricks');
INSERT INTO activity (code, mets, heading, description) VALUES (11060, 8.0, 'occupation', 'carrying moderate loads up stairs, moving boxes (16-40 pounds)');
INSERT INTO activity (code, mets, heading, description) VALUES (11070, 2.5, 'occupation', 'chambermaid, making bed (nursing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11080, 6.5, 'occupation', 'coal mining, drilling coal, rock');
INSERT INTO activity (code, mets, heading, description) VALUES (11090, 6.5, 'occupation', 'coal mining, erecting supports');
INSERT INTO activity (code, mets, heading, description) VALUES (11100, 6.0, 'occupation', 'coal mining, general');
INSERT INTO activity (code, mets, heading, description) VALUES (11110, 7.0, 'occupation', 'coal mining, shoveling coal');
INSERT INTO activity (code, mets, heading, description) VALUES (11120, 5.5, 'occupation', 'construction, outside, remodeling');
INSERT INTO activity (code, mets, heading, description) VALUES (11121, 3.0, 'occupation', 'custodial work - buffing the floor with electric buffer');
INSERT INTO activity (code, mets, heading, description) VALUES (11122, 2.5, 'occupation', 'custodial work - cleaning sink and toilet, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11123, 2.5, 'occupation', 'custodial work - dusting, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11124, 4.0, 'occupation', 'custodial work – feathering arena floor, moderate effor');
INSERT INTO activity (code, mets, heading, description) VALUES (11125, 3.5, 'occupation', 'custodial work - general cleaning, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11126, 3.5, 'occupation', 'custodial work - mopping, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11127, 3.0, 'occupation', 'custodial work - take out trash, moderate effor');
INSERT INTO activity (code, mets, heading, description) VALUES (11128, 2.5, 'occupation', 'custodial work - vacuuming, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11129, 3.0, 'occupation', 'custodial work - vacuuming, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11130, 3.5, 'occupation', 'electrical work, plumbing');
INSERT INTO activity (code, mets, heading, description) VALUES (11140, 8.0, 'occupation', 'farming, baling hay, cleaning barn, poultry work,vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11150, 3.5, 'occupation', 'farming, chasing cattle, non-strenuous(walking), moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11151, 4.0, 'occupation', 'farming, chasing cattle or other livestock on horseback, moderate effor');
INSERT INTO activity (code, mets, heading, description) VALUES (11152, 2.0, 'occupation', 'farming, chasing cattle or other livestock, driving, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11160, 2.5, 'occupation', 'farming, driving harvester, cutting hay, irrigation work');
INSERT INTO activity (code, mets, heading, description) VALUES (11170, 2.5, 'occupation', 'farming, driving tractor');
INSERT INTO activity (code, mets, heading, description) VALUES (11180, 4.0, 'occupation', 'farming, feeding small animals');
INSERT INTO activity (code, mets, heading, description) VALUES (11190, 4.5, 'occupation', 'farming, feeding cattle, horses');
INSERT INTO activity (code, mets, heading, description) VALUES (11191, 4.5, 'occupation', 'farming, hauling water for animals, general hauling water');
INSERT INTO activity (code, mets, heading, description) VALUES (11192, 6.0, 'occupation', 'farming, taking care of animals (grooming, brushing, shearing sheep, assisting with birthing, medical care, branding)');
INSERT INTO activity (code, mets, heading, description) VALUES (11200, 8.0, 'occupation', 'farming, forking straw bales, cleaning corral or barn, vigorous effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11210, 3.0, 'occupation', 'farming, milking by hand, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11220, 1.5, 'occupation', 'farming, milking by machine, light effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11230, 5.5, 'occupation', 'farming, shoveling grain, moderate effort');
INSERT INTO activity (code, mets, heading, description) VALUES (11240, 12.0, 'occupation', 'fire fighter, general');
INSERT INTO activity (code, mets, heading, description) VALUES (11245, 11.0, 'occupation', 'fire fighter, climbing ladder with full gear');
INSERT INTO activity (code, mets, heading, description) VALUES (11246, 8.0, 'occupation', 'fire fighter, hauling hoses on ground');
INSERT INTO activity (code, mets, heading, description) VALUES (11250, 17.0, 'occupation', 'forestry, ax chopping, fast');
INSERT INTO activity (code, mets, heading, description) VALUES (11260, 5.0, 'occupation', 'forestry, ax chopping, slow');
INSERT INTO activity (code, mets, heading, description) VALUES (11270, 7.0, 'occupation', 'forestry, barking trees');
INSERT INTO activity (code, mets, heading, description) VALUES (11280, 11.0, 'occupation', 'forestry, carrying logs');
INSERT INTO activity (code, mets, heading, description) VALUES (11290, 8.0, 'occupation', 'forestry, felling trees');
INSERT INTO activity (code, mets, heading, description) VALUES (11300, 8.0, 'occupation', 'forestry, general');
INSERT INTO activity (code, mets, heading, description) VALUES (11310, 5.0, 'occupation', 'forestry, hoeing');
INSERT INTO activity (code, mets, heading, description) VALUES (11320, 6.0, 'occupation', 'forestry, planting by hand');
INSERT INTO activity (code, mets, heading, description) VALUES (11330, 7.0, 'occupation', 'forestry, sawing by hand');
INSERT INTO activity (code, mets, heading, description) VALUES (11340, 4.5, 'occupation', 'forestry, sawing, power');
INSERT INTO activity (code, mets, heading, description) VALUES (11350, 9.0, 'occupation', 'forestry, trimming trees');
INSERT INTO activity (code, mets, heading, description) VALUES (11360, 4.0, 'occupation', 'forestry, weeding');
INSERT INTO activity (code, mets, heading, description) VALUES (11370, 4.5, 'occupation', 'furriery');
INSERT INTO activity (code, mets, heading, description) VALUES (11380, 6.0, 'occupation', 'horse grooming');
INSERT INTO activity (code, mets, heading, description) VALUES (11390, 8.0, 'occupation', 'horse racing, galloping');
INSERT INTO activity (code, mets, heading, description) VALUES (11400, 6.5, 'occupation', 'horse racing, trotting');
INSERT INTO activity (code, mets, heading, description) VALUES (11410, 2.6, 'occupation', 'horse racing, walking');
INSERT INTO activity (code, mets, heading, description) VALUES (11420, 3.5, 'occupation', 'locksmith');
INSERT INTO activity (code, mets, heading, description) VALUES (11430, 2.5, 'occupation', 'machine tooling, machining, working sheet meta');
INSERT INTO activity (code, mets, heading, description) VALUES (11440, 3.0, 'occupation', 'machine tooling, operating lathe');
INSERT INTO activity (code, mets, heading, description) VALUES (11450, 5.0, 'occupation', 'machine tooling, operating punch press');
INSERT INTO activity (code, mets, heading, description) VALUES (11460, 4.0, 'occupation', 'machine tooling, tapping and drilling');
INSERT INTO activity (code, mets, heading, description) VALUES (11470, 3.0, 'occupation', 'machine tooling, welding');
INSERT INTO activity (code, mets, heading, description) VALUES (11480, 7.0, 'occupation', 'masonry, concrete');
INSERT INTO activity (code, mets, heading, description) VALUES (11485, 4.0, 'occupation', 'masseur, masseuse (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11490, 7.5, 'occupation', 'moving, pushing heavy objects, 75 lbs or more (desks, moving van work)');
INSERT INTO activity (code, mets, heading, description) VALUES (11495, 12.0, 'occupation', 'skindiving or SCUBA diving as a frogman (Navy Seal)');
INSERT INTO activity (code, mets, heading, description) VALUES (11500, 2.5, 'occupation', 'operating heavy duty equipment/automated, not driving');
INSERT INTO activity (code, mets, heading, description) VALUES (11510, 4.5, 'occupation', 'orange grove work');
INSERT INTO activity (code, mets, heading, description) VALUES (11520, 2.3, 'occupation', 'printing (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11525, 2.5, 'occupation', 'police, directing traffic (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11526, 2.0, 'occupation', 'police, driving a squad car (sitting)');
INSERT INTO activity (code, mets, heading, description) VALUES (11527, 1.3, 'occupation', 'police, riding in a squad car (sitting)');
INSERT INTO activity (code, mets, heading, description) VALUES (11528, 4.0, 'occupation', 'police, making an arrest (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11530, 2.5, 'occupation', 'shoe repair, general');
INSERT INTO activity (code, mets, heading, description) VALUES (11540, 8.5, 'occupation', 'shoveling, digging ditches');
INSERT INTO activity (code, mets, heading, description) VALUES (11550, 9.0, 'occupation', 'shoveling, heavy (more than 16 pounds/minute');
INSERT INTO activity (code, mets, heading, description) VALUES (11560, 6.0, 'occupation', 'shoveling, light (less than 10 pounds/minute)');
INSERT INTO activity (code, mets, heading, description) VALUES (11570, 7.0, 'occupation', 'shoveling, moderate (10 to 15 pounds/minute)');
INSERT INTO activity (code, mets, heading, description) VALUES (11580, 1.5, 'occupation', 'sitting - light office work, general (chemistry lab work, light use of hand tools, watch repair or micro-assembly, light assembly/repair), sitting, reading, driving at work');
INSERT INTO activity (code, mets, heading, description) VALUES (11585, 1.5, 'occupation', 'sitting meetings, general, and/or with talking involved,eatting at a business meeting');
INSERT INTO activity (code, mets, heading, description) VALUES (11590, 2.5, 'occupation', 'sitting; moderate (heavy levers, riding mower/forklift, crane operation) teaching stretching or yoga');
INSERT INTO activity (code, mets, heading, description) VALUES (11600, 2.3, 'occupation', 'standing; light (bartending, store clerk, assembling, filing, duplicating, putting up a Christmas tree), standing and talking at work, changing clothes when teaching physical education');
INSERT INTO activity (code, mets, heading, description) VALUES (11610, 3.0, 'occupation', 'standing; light/moderate (assemble/repair heavy parts, welding, stocking, auto repair, pack boxes for moving, etc.), patient care (as in nursing');
INSERT INTO activity (code, mets, heading, description) VALUES (11615, 4.0, 'occupation', 'lifting items continuously, 10 – 20 lbs, with limited walking or resting');
INSERT INTO activity (code, mets, heading, description) VALUES (11620, 3.5, 'occupation', 'standing; moderate (assembling at fast rate, intermittent, lifting 50 lbs, hitch/twisting ropes)');
INSERT INTO activity (code, mets, heading, description) VALUES (11630, 4.0, 'occupation', 'standing; moderate/heavy (lifting more than 50 lbs, masonry, painting, paper hanging');
INSERT INTO activity (code, mets, heading, description) VALUES (11640, 5.0, 'occupation', 'steel mill, fettling');
INSERT INTO activity (code, mets, heading, description) VALUES (11650, 5.5, 'occupation', 'steel mill, forging');
INSERT INTO activity (code, mets, heading, description) VALUES (11660, 8.0, 'occupation', 'steel mill, hand rolling');
INSERT INTO activity (code, mets, heading, description) VALUES (11670, 8.0, 'occupation', 'steel mill, merchant mill rolling');
INSERT INTO activity (code, mets, heading, description) VALUES (11680, 11.0, 'occupation', 'steel mill, removing slag');
INSERT INTO activity (code, mets, heading, description) VALUES (11690, 7.5, 'occupation', 'steel mill, tending furnace');
INSERT INTO activity (code, mets, heading, description) VALUES (11700, 5.5, 'occupation', 'steel mill, tipping molds');
INSERT INTO activity (code, mets, heading, description) VALUES (11710, 8.0, 'occupation', 'steel mill, working in general');
INSERT INTO activity (code, mets, heading, description) VALUES (11720, 2.5, 'occupation', 'tailoring, cutting');
INSERT INTO activity (code, mets, heading, description) VALUES (11730, 2.5, 'occupation', 'tailoring, general');
INSERT INTO activity (code, mets, heading, description) VALUES (11740, 2.0, 'occupation', 'tailoring, hand sewing');
INSERT INTO activity (code, mets, heading, description) VALUES (11750, 2.5, 'occupation', 'tailoring, machine sewing');
INSERT INTO activity (code, mets, heading, description) VALUES (11760, 4.0, 'occupation', 'tailoring, pressing');
INSERT INTO activity (code, mets, heading, description) VALUES (11765, 3.5, 'occupation', 'tailoring, weaving');
INSERT INTO activity (code, mets, heading, description) VALUES (11766, 6.5, 'occupation', 'truck driving, loading and unloading truck (standing)');
INSERT INTO activity (code, mets, heading, description) VALUES (11770, 1.5, 'occupation', 'typing, electric, manual or computer');
INSERT INTO activity (code, mets, heading, description) VALUES (11780, 6.0, 'occupation', 'using heavy power tools such as pneumatic tools (jackhammers, drills, etc.');
INSERT INTO activity (code, mets, heading, description) VALUES (11790, 8.0, 'occupation', 'using heavy tools (not power) such as shovel, pick, tunnel bar, spade');
INSERT INTO activity (code, mets, heading, description) VALUES (11791, 2.0, 'occupation', 'walking on job, less than 2.0 mph (in office or lab area), very slow');
INSERT INTO activity (code, mets, heading, description) VALUES (11792, 3.3, 'occupation', 'walking on job, 3.0 mph, in office, moderate speed, not carrying anything');
INSERT INTO activity (code, mets, heading, description) VALUES (11793, 3.8, 'occupation', 'walking on job, 3.5 mph, in office, brisk speed, not carrying anything');
INSERT INTO activity (code, mets, heading, description) VALUES (11795, 3.0, 'occupation', 'walking, 2.5 mph, slowly and carrying light objects less than 25 pounds');
INSERT INTO activity (code, mets, heading, description) VALUES (11796, 3.0, 'occupation', 'walking, gathering things at work, ready to leave');
INSERT INTO activity (code, mets, heading, description) VALUES (11800, 4.0, 'occupation', 'walking, 3.0 mph, moderately and carrying light objects less than 25 lbs');

--INSERT INTO activity (code, mets, heading, description) VALUES (11420, 3.5, 'occupation', 'locksmith');
--INSERT INTO activity (code, mets, heading, description) VALUES (11430, 2.5, 'occupation', 'machine tooling, machining, working sheet meta');
--INSERT INTO activity (code, mets, heading, description) VALUES (11440, 3.0, 'occupation', 'machine tooling, operating lathe');
--INSERT INTO activity (code, mets, heading, description) VALUES (11450, 5.0, 'occupation', 'machine tooling, operating punch press');
--INSERT INTO activity (code, mets, heading, description) VALUES (11460, 4.0, 'occupation', 'machine tooling, tapping and drilling');
--INSERT INTO activity (code, mets, heading, description) VALUES (11470, 3.0, 'occupation', 'machine tooling, welding');
--INSERT INTO activity (code, mets, heading, description) VALUES (11480, 7.0, 'occupation', 'masonry, concrete');
--INSERT INTO activity (code, mets, heading, description) VALUES (11485, 4.0, 'occupation', 'masseur, masseuse (standing)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11490, 7.5, 'occupation', 'moving, pushing heavy objects, 75 lbs or more (desks, moving van work)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11495, 12.0, 'occupation', 'skindiving or SCUBA diving as a frogman (Navy Seal)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11500, 2.5, 'occupation', 'operating heavy duty equipment/automated, not driving');
--INSERT INTO activity (code, mets, heading, description) VALUES (11510, 4.5, 'occupation', 'orange grove work');
--INSERT INTO activity (code, mets, heading, description) VALUES (11520, 2.3, 'occupation', 'printing (standing)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11525, 2.5, 'occupation', 'police, directing traffic (standing)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11526, 2.0, 'occupation', 'police, driving a squad car (sitting)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11527, 1.3, 'occupation', 'police, riding in a squad car (sitting)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11528, 4.0, 'occupation', 'police, making an arrest (standing)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11530, 2.5, 'occupation', 'shoe repair, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (11540, 8.5, 'occupation', 'shoveling, digging ditches');
--INSERT INTO activity (code, mets, heading, description) VALUES (11550, 9.0, 'occupation', 'shoveling, heavy (more than 16 pounds/minute');
--INSERT INTO activity (code, mets, heading, description) VALUES (11560, 6.0, 'occupation', 'shoveling, light (less than 10 pounds/minute)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11570, 7.0, 'occupation', 'shoveling, moderate (10 to 15 pounds/minute)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11580, 1.5, 'occupation', 'sitting - light office work, general (chemistry lab work, light use of hand tools, watch repair or micro-assembly, light assembly/repair), sitting, reading, driving at work');
--INSERT INTO activity (code, mets, heading, description) VALUES (11585, 1.5, 'occupation', 'sitting meetings, general, and/or with talking involved,eatting at a business meeting');
--INSERT INTO activity (code, mets, heading, description) VALUES (11590, 2.5, 'occupation', 'sitting; moderate (heavy levers, riding mower/forklift, crane operation) teaching stretching or yoga');
--INSERT INTO activity (code, mets, heading, description) VALUES (11600, 2.3, 'occupation', 'standing; light (bartending, store clerk, assembling, filing, duplicating, putting up a Christmas tree), standing and talking at work, changing clothes when teaching physical education');
--INSERT INTO activity (code, mets, heading, description) VALUES (11610, 3.0, 'occupation', 'standing; light/moderate (assemble/repair heavy parts, welding, stocking, auto repair, pack boxes for moving, etc.), patient care (as in nursing');
--INSERT INTO activity (code, mets, heading, description) VALUES (11615, 4.0, 'occupation', 'lifting items continuously, 10 – 20 lbs, with limited walking or resting');
--INSERT INTO activity (code, mets, heading, description) VALUES (11620, 3.5, 'occupation', 'standing; moderate (assembling at fast rate, intermittent, lifting 50 lbs, hitch/twisting ropes)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11630, 4.0, 'occupation', 'standing; moderate/heavy (lifting more than 50 lbs, masonry, painting, paper hanging');
--INSERT INTO activity (code, mets, heading, description) VALUES (11640, 5.0, 'occupation', 'steel mill, fettling');
--INSERT INTO activity (code, mets, heading, description) VALUES (11650, 5.5, 'occupation', 'steel mill, forging');
--INSERT INTO activity (code, mets, heading, description) VALUES (11660, 8.0, 'occupation', 'steel mill, hand rolling');
--INSERT INTO activity (code, mets, heading, description) VALUES (11670, 8.0, 'occupation', 'steel mill, merchant mill rolling');
--INSERT INTO activity (code, mets, heading, description) VALUES (11680, 11.0, 'occupation', 'steel mill, removing slag');
--INSERT INTO activity (code, mets, heading, description) VALUES (11690, 7.5, 'occupation', 'steel mill, tending furnace');
--INSERT INTO activity (code, mets, heading, description) VALUES (11700, 5.5, 'occupation', 'steel mill, tipping molds');
--INSERT INTO activity (code, mets, heading, description) VALUES (11710, 8.0, 'occupation', 'steel mill, working in general');
--INSERT INTO activity (code, mets, heading, description) VALUES (11720, 2.5, 'occupation', 'tailoring, cutting');
--INSERT INTO activity (code, mets, heading, description) VALUES (11730, 2.5, 'occupation', 'tailoring, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (11740, 2.0, 'occupation', 'tailoring, hand sewing');
--INSERT INTO activity (code, mets, heading, description) VALUES (11750, 2.5, 'occupation', 'tailoring, machine sewing');
--INSERT INTO activity (code, mets, heading, description) VALUES (11760, 4.0, 'occupation', 'tailoring, pressing');
--INSERT INTO activity (code, mets, heading, description) VALUES (11765, 3.5, 'occupation', 'tailoring, weaving');
--INSERT INTO activity (code, mets, heading, description) VALUES (11766, 6.5, 'occupation', 'truck driving, loading and unloading truck (standing)');
--INSERT INTO activity (code, mets, heading, description) VALUES (11770, 1.5, 'occupation', 'typing, electric, manual or computer');
--INSERT INTO activity (code, mets, heading, description) VALUES (11780, 6.0, 'occupation', 'using heavy power tools such as pneumatic tools (jackhammers, drills, etc.');
--INSERT INTO activity (code, mets, heading, description) VALUES (11790, 8.0, 'occupation', 'using heavy tools (not power) such as shovel, pick, tunnel bar, spade');
--INSERT INTO activity (code, mets, heading, description) VALUES (11791, 2.0, 'occupation', 'walking on job, less than 2.0 mph (in office or lab area), very slow');
--INSERT INTO activity (code, mets, heading, description) VALUES (11792, 3.3, 'occupation', 'walking on job, 3.0 mph, in office, moderate speed, not carrying anything');
--INSERT INTO activity (code, mets, heading, description) VALUES (11793, 3.8, 'occupation', 'walking on job, 3.5 mph, in office, brisk speed, not carrying anything');
--INSERT INTO activity (code, mets, heading, description) VALUES (11795, 3.0, 'occupation', 'walking, 2.5 mph, slowly and carrying light objects less than 25 pounds');
--INSERT INTO activity (code, mets, heading, description) VALUES (11796, 3.0, 'occupation', 'walking, gathering things at work, ready to leave');
--INSERT INTO activity (code, mets, heading, description) VALUES (11800, 4.0, 'occupation', 'walking, 3.0 mph, moderately and carrying light objects less than 25 lbs');
--INSERT INTO activity (code, mets, heading, description) VALUES (15110, 6.0, 'sports', 'boxing, punching bag');
--INSERT INTO activity (code, mets, heading, description) VALUES (15120, 9.0, 'sports', 'boxing, sparring');
--INSERT INTO activity (code, mets, heading, description) VALUES (15130, 7.0, 'sports', 'broomball');
--INSERT INTO activity (code, mets, heading, description) VALUES (15135, 5.0, 'sports', 'children’s games (hopscotch, 4-square, dodge ball, playground apparatus, t-ball, tetherball, marbles, jacks, acrace games');
--INSERT INTO activity (code, mets, heading, description) VALUES (15140, 4.0, 'sports', 'coaching: football, soccer, basketball, baseball, swimming, etc.');
--INSERT INTO activity (code, mets, heading, description) VALUES (15150, 5.0, 'sports', 'cricket (batting, bowling)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15160, 2.5, 'sports', 'croquet');
--INSERT INTO activity (code, mets, heading, description) VALUES (15170, 4.0, 'sports', 'curling');
--INSERT INTO activity (code, mets, heading, description) VALUES (15180, 2.5, 'sports', 'darts, wall or lawn');
--INSERT INTO activity (code, mets, heading, description) VALUES (15190, 6.0, 'sports', 'drag racing, pushing or driving a car');
--INSERT INTO activity (code, mets, heading, description) VALUES (15200, 6.0, 'sports', 'fencing');
--INSERT INTO activity (code, mets, heading, description) VALUES (15210, 9.0, 'sports', 'football, competitive');
--INSERT INTO activity (code, mets, heading, description) VALUES (15230, 8.0, 'sports', 'football, touch, flag, general (Taylor Code 510');
--INSERT INTO activity (code, mets, heading, description) VALUES (15235, 2.5, 'sports', 'football or baseball, playing catch');
--INSERT INTO activity (code, mets, heading, description) VALUES (15240, 3.0, 'sports', 'frisbee playing, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15250, 8.0, 'sports', 'frisbee, ultimate');
--INSERT INTO activity (code, mets, heading, description) VALUES (15255, 4.5, 'sports', 'golf, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15256,  0.0, 'sports', 'golf carrying clubs');
--INSERT INTO activity (code, mets, heading, description) VALUES (15265, 4.5, 'sports', 'golf, walking and carrying clubs (See footnote at end of the Compendium');
--INSERT INTO activity (code, mets, heading, description) VALUES (15270, 3.0, 'sports', 'golf, miniature, driving range');
--INSERT INTO activity (code, mets, heading, description) VALUES (15257,  0.0, 'sports', 'golf, pulling clubs');
--INSERT INTO activity (code, mets, heading, description) VALUES (15285, 4.3, 'sports', 'golf, walking and pulling clubs (See footnote at end of the Compendium');
--INSERT INTO activity (code, mets, heading, description) VALUES (15290, 3.5, 'sports', 'golf, using power cart (Taylor Code 070)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15300, 4.0, 'sports', 'gymnastics, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15310, 4.0, 'sports', 'hacky sack');
--INSERT INTO activity (code, mets, heading, description) VALUES (15320, 12.0, 'sports', 'handball, general (Taylor Code 520)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15330, 8.0, 'sports', 'handball, team');
--INSERT INTO activity (code, mets, heading, description) VALUES (15340, 3.5, 'sports', 'hand gliding');
--INSERT INTO activity (code, mets, heading, description) VALUES (15350, 8.0, 'sports', 'hockey, field');
--INSERT INTO activity (code, mets, heading, description) VALUES (15360, 8.0, 'sports', 'hockey, ice');
--INSERT INTO activity (code, mets, heading, description) VALUES (15370, 4.0, 'sports', 'horseback riding, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15380, 3.5, 'sports', 'horseback riding, saddling horse, grooming horse');
--INSERT INTO activity (code, mets, heading, description) VALUES (15390, 6.5, 'sports', 'horseback riding, trotting');
--INSERT INTO activity (code, mets, heading, description) VALUES (15400, 2.5, 'sports', 'horseback riding, walking');
--INSERT INTO activity (code, mets, heading, description) VALUES (15410, 3.0, 'sports', 'horseshoe pitching, quoits');
--INSERT INTO activity (code, mets, heading, description) VALUES (15420, 12.0, 'sports', 'jai alai');
--INSERT INTO activity (code, mets, heading, description) VALUES (15430, 10.0, 'sports', 'judo, jujitsu, karate, kick boxing, tae kwan do');
--INSERT INTO activity (code, mets, heading, description) VALUES (15440, 4.0, 'sports', 'juggling');
--INSERT INTO activity (code, mets, heading, description) VALUES (15450, 7.0, 'sports', 'kickball');
--INSERT INTO activity (code, mets, heading, description) VALUES (15460, 8.0, 'sports', 'lacrosse');
--INSERT INTO activity (code, mets, heading, description) VALUES (15470, 4.0, 'sports', 'motor-cross');
--INSERT INTO activity (code, mets, heading, description) VALUES (15480, 9.0, 'sports', 'orienteering');
--INSERT INTO activity (code, mets, heading, description) VALUES (15490, 10.0, 'sports', 'paddleball, competitive');
--INSERT INTO activity (code, mets, heading, description) VALUES (15500, 6.0, 'sports', 'paddleball, casual, general (Taylor Code 460)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15510, 8.0, 'sports', 'polo');
--INSERT INTO activity (code, mets, heading, description) VALUES (15520, 10.0, 'sports', 'racquetball, competitive');
--INSERT INTO activity (code, mets, heading, description) VALUES (15530, 7.0, 'sports', 'racquetball, casual, general (Taylor Code 470)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15535, 11.0, 'sports', 'rock climbing, ascending rock');
--INSERT INTO activity (code, mets, heading, description) VALUES (15540, 8.0, 'sports', 'rock climbing, rappelling');
--INSERT INTO activity (code, mets, heading, description) VALUES (15550, 12.0, 'sports', 'rope jumping, fast');
--INSERT INTO activity (code, mets, heading, description) VALUES (15551, 10.0, 'sports', 'rope jumping, moderate, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15552, 8.0, 'sports', 'rope jumping, slow');
--INSERT INTO activity (code, mets, heading, description) VALUES (15560, 10.0, 'sports', 'rugby');
--INSERT INTO activity (code, mets, heading, description) VALUES (15570, 3.0, 'sports', 'shuffleboard, lawn bowling');
--INSERT INTO activity (code, mets, heading, description) VALUES (15580, 5.0, 'sports', 'skateboarding');
--INSERT INTO activity (code, mets, heading, description) VALUES (15590, 7.0, 'sports', 'skating, roller (Taylor Code 360)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15591, 12.0, 'sports', 'roller blading (in-line skating)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15600, 3.5, 'sports', 'sky diving');
--INSERT INTO activity (code, mets, heading, description) VALUES (15605, 10.0, 'sports', 'soccer, competitive');
--INSERT INTO activity (code, mets, heading, description) VALUES (15610, 7.0, 'sports', 'soccer, casual, general (Taylor Code 540)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15620, 5.0, 'sports', 'softball or baseball, fast or slow pitch, general (Taylor Code 440)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15630, 4.0, 'sports', 'softball, officiating');
--INSERT INTO activity (code, mets, heading, description) VALUES (15640, 6.0, 'sports', 'softball, pitching');
--INSERT INTO activity (code, mets, heading, description) VALUES (15650, 12.0, 'sports', 'squash (Taylor Code 530)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15660, 4.0, 'sports', 'table tennis, ping pong (Taylor Code 410)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15670, 4.0, 'sports', 'tai chi');
--INSERT INTO activity (code, mets, heading, description) VALUES (15675, 7.0, 'sports', 'tennis, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15680, 6.0, 'sports', 'tennis, doubles (Taylor Code 430)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15685, 5.0, 'sports', 'tennis, doubles');
--INSERT INTO activity (code, mets, heading, description) VALUES (15690, 8.0, 'sports', 'tennis, singles (Taylor Code 420)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15700, 3.5, 'sports', 'trampoline');
--INSERT INTO activity (code, mets, heading, description) VALUES (15710, 4.0, 'sports', 'volleyball (Taylor Code 400)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15711, 8.0, 'sports', 'volleyball, competitive, in gymnasium');
--INSERT INTO activity (code, mets, heading, description) VALUES (15720, 3.0, 'sports', 'volleyball, non-competitive, 6 - 9 member team, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15725, 8.0, 'sports', 'volleyball, beach');
--INSERT INTO activity (code, mets, heading, description) VALUES (15730, 6.0, 'sports', 'wrestling (one match = 5 minutes)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15731, 7.0, 'sports', 'wallyball, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (15732, 4.0, 'sports', 'track and field (shot, discus, hammer throw)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15733, 6.0, 'sports', 'track and field (high jump, long jump, triple jump, javelin, pole vault)');
--INSERT INTO activity (code, mets, heading, description) VALUES (15734, 10.0, 'sports', 'track and field (steeplechase, hurdles)');
--INSERT INTO activity (code, mets, heading, description) VALUES (16010, 2.0, 'transportation', 'automobile or light truck (not a semi) driving');
--INSERT INTO activity (code, mets, heading, description) VALUES (16015, 1.0, 'transportation', 'riding in a car or truck');
--INSERT INTO activity (code, mets, heading, description) VALUES (16016, 1.0, 'transportation', 'riding in a bus');
--INSERT INTO activity (code, mets, heading, description) VALUES (16020, 2.0, 'transportation', 'flying airplane');
--INSERT INTO activity (code, mets, heading, description) VALUES (16030, 2.5, 'transportation', 'motor scooter, motorcycle');
--INSERT INTO activity (code, mets, heading, description) VALUES (16040, 6.0, 'transportation', 'pushing plane in and out of hangar');
--INSERT INTO activity (code, mets, heading, description) VALUES (16050, 3.0, 'transportation', 'driving heavy truck, tractor, bus');
--INSERT INTO activity (code, mets, heading, description) VALUES (17010, 7.0, 'walking', 'backpacking (Taylor Code 050)');
--INSERT INTO activity (code, mets, heading, description) VALUES (17020, 3.5, 'walking', 'carrying infant or 15 pound load (e.g. suitcase), level ground or downstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17025, 9.0, 'walking', 'carrying load upstairs, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (17026, 5.0, 'walking', 'carrying 1 to 15 lb load, upstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17027, 6.0, 'walking', 'carrying 16 to 24 lb load, upstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17028, 8.0, 'walking', 'carrying 25 to 49 lb load, upstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17029, 10.0, 'walking', 'carrying 50 to 74 lb load, upstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17030, 12.0, 'walking', 'carrying 74+ lb load, upstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17031, 3.0, 'walking', 'loading /unloading a car');
--INSERT INTO activity (code, mets, heading, description) VALUES (17035, 7.0, 'walking', 'climbing hills with 0 to 9 pound load');
--INSERT INTO activity (code, mets, heading, description) VALUES (17040, 7.5, 'walking', 'climbing hills with 10 to 20 pound load');
--INSERT INTO activity (code, mets, heading, description) VALUES (17050, 8.0, 'walking', 'climbing hills with 21 to 42 pound load');
--INSERT INTO activity (code, mets, heading, description) VALUES (17060, 9.0, 'walking', 'climbing hills with 42+ pound load');
--INSERT INTO activity (code, mets, heading, description) VALUES (17070, 3.0, 'walking', 'downstairs');
--INSERT INTO activity (code, mets, heading, description) VALUES (17080, 6.0, 'walking', 'hiking, cross country (Taylor Code 040)');
--INSERT INTO activity (code, mets, heading, description) VALUES (17085, 2.5, 'walking', 'bird watching');
--INSERT INTO activity (code, mets, heading, description) VALUES (17090, 6.5, 'walking', 'marching, rapidly, military');
--INSERT INTO activity (code, mets, heading, description) VALUES (17100, 2.5, 'walking', 'pushing or pulling stroller with child or walking with children');
--INSERT INTO activity (code, mets, heading, description) VALUES (17105, 4.0, 'walking', 'pushing a wheelchair, non-occupational setting');
--INSERT INTO activity (code, mets, heading, description) VALUES (17110, 6.5, 'walking', 'race walking');
--INSERT INTO activity (code, mets, heading, description) VALUES (17120, 8.0, 'walking', 'rock or mountain climbing (Taylor Code 060)');
--INSERT INTO activity (code, mets, heading, description) VALUES (17130, 8.0, 'walking', 'up stairs, using or climbing up ladder (Taylor Code 030)');
--INSERT INTO activity (code, mets, heading, description) VALUES (17140, 5.0, 'walking', 'using crutches');
--INSERT INTO activity (code, mets, heading, description) VALUES (17150, 2.0, 'walking', 'walking, household walking');
--INSERT INTO activity (code, mets, heading, description) VALUES (17151, 2.0, 'walking', 'walking, less than 2.0 mph, level ground, strolling, very slow');
--INSERT INTO activity (code, mets, heading, description) VALUES (17152, 2.5, 'walking', 'walking, 2.0 mph, level, slow pace, firm surface');
--INSERT INTO activity (code, mets, heading, description) VALUES (17160, 3.5, 'walking', 'walking for pleasure (Taylor Code 010)');
--INSERT INTO activity (code, mets, heading, description) VALUES (17161, 2.5, 'walking', 'walking from house to car or bus, from car or bus to go places, from car or bus to and from the worksite');
--INSERT INTO activity (code, mets, heading, description) VALUES (17162, 2.5, 'walking', 'walking to neighbor’s house or family’s house for social reasons');
--INSERT INTO activity (code, mets, heading, description) VALUES (17165, 3.0, 'walking', 'walking the dog');
--INSERT INTO activity (code, mets, heading, description) VALUES (17170, 3.0, 'walking', 'walking, 2.5 mph, firm surface');
--INSERT INTO activity (code, mets, heading, description) VALUES (17180, 2.8, 'walking', 'walking, 2.5 mph, downhill');
--INSERT INTO activity (code, mets, heading, description) VALUES (17190, 3.3, 'walking', 'walking, 3.0 mph, level, moderate pace, firm surface');
--INSERT INTO activity (code, mets, heading, description) VALUES (17200, 3.8, 'walking', 'walking, 3.5 mph, level, brisk, firm surface, walking for exercise');
--INSERT INTO activity (code, mets, heading, description) VALUES (17210, 6.0, 'walking', 'walking, 3.5 mph, uphill');
--INSERT INTO activity (code, mets, heading, description) VALUES (17220, 5.0, 'walking', 'walking, 4.0 mph, level, firm surface, very brisk pace');
--INSERT INTO activity (code, mets, heading, description) VALUES (17230, 6.3, 'walking', 'walking, 4.5 mph, level, firm surface, very, very brisk');
--INSERT INTO activity (code, mets, heading, description) VALUES (17231, 8.0, 'walking', 'walking, 5.0 mph');
--INSERT INTO activity (code, mets, heading, description) VALUES (17250, 3.5, 'walking', 'walking, for pleasure, work break');
--INSERT INTO activity (code, mets, heading, description) VALUES (17260, 5.0, 'walking', 'walking, grass track');
--INSERT INTO activity (code, mets, heading, description) VALUES (17270, 4.0, 'walking', 'walking, to work or class (Taylor Code 015)');
--INSERT INTO activity (code, mets, heading, description) VALUES (17280, 2.5, 'walking', 'walking to and from an outhouse');
--INSERT INTO activity (code, mets, heading, description) VALUES (18010, 2.5, 'water activities', 'boating, power');
--INSERT INTO activity (code, mets, heading, description) VALUES (18020, 4.0, 'water activities', 'canoeing, on camping trip (Taylor Code 270)');
--INSERT INTO activity (code, mets, heading, description) VALUES (18025, 3.3, 'water activities', 'canoeing, harvesting wild rice, knocking rice off the stalks');
--INSERT INTO activity (code, mets, heading, description) VALUES (18030, 7.0, 'water activities', 'canoeing, portaging');
--INSERT INTO activity (code, mets, heading, description) VALUES (18040, 3.0, 'water activities', 'canoeing, rowing, 2.0-3.9 mph, light effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18050, 7.0, 'water activities', 'canoeing, rowing, 4.0-5.9 mph, moderate effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18060, 12.0, 'water activities', 'canoeing, rowing, >6 mph, vigorous effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18070, 3.5, 'water activities', 'canoeing, rowing, for pleasure, general (Taylor Code 250');
--INSERT INTO activity (code, mets, heading, description) VALUES (18080, 12.0, 'water activities', 'canoeing, rowing, in competition, or crew or sculling (Taylor Code 260');
--INSERT INTO activity (code, mets, heading, description) VALUES (18090, 3.0, 'water activities', 'diving, springboard or platform');
--INSERT INTO activity (code, mets, heading, description) VALUES (18100, 5.0, 'water activities', 'kayaking');
--INSERT INTO activity (code, mets, heading, description) VALUES (18110, 4.0, 'water activities', 'paddle boat');
--INSERT INTO activity (code, mets, heading, description) VALUES (18120, 3.0, 'water activities', 'sailing, boat and board sailing, windsurfing, ice sailing, general (Taylor Code 235)');
--INSERT INTO activity (code, mets, heading, description) VALUES (18130, 5.0, 'water activities', 'sailing, in competition');
--INSERT INTO activity (code, mets, heading, description) VALUES (18140, 3.0, 'water activities', 'sailing, Sunfish/Laser/Hobby Cat, Keel boats, ocean sailing, yachting');
--INSERT INTO activity (code, mets, heading, description) VALUES (18150, 6.0, 'water activities', 'skiing, water (Taylor Code 220)');
--INSERT INTO activity (code, mets, heading, description) VALUES (18160, 7.0, 'water activities', 'skimobiling');
--INSERT INTO activity (code, mets, heading, description) VALUES (15258,  , 'water activities', '');
--INSERT INTO activity (code, mets, heading, description) VALUES (18180, 16.0, 'water activities', 'skindiving, fast');
--INSERT INTO activity (code, mets, heading, description) VALUES (18190, 12.5, 'water activities', 'skindiving, moderate');
--INSERT INTO activity (code, mets, heading, description) VALUES (18200, 7.0, 'water activities', 'skindiving, scuba diving, general (Taylor Code 310)');
--INSERT INTO activity (code, mets, heading, description) VALUES (18210, 5.0, 'water activities', 'snorkeling (Taylor Code 320)');
--INSERT INTO activity (code, mets, heading, description) VALUES (18220, 3.0, 'water activities', 'surfing, body or board');
--INSERT INTO activity (code, mets, heading, description) VALUES (18230, 10.0, 'water activities', 'swimming laps, freestyle, fast, vigorous effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18240, 7.0, 'water activities', 'swimming laps, freestyle, slow, moderate or light effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18250, 7.0, 'water activities', 'swimming, backstroke, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (18260, 10.0, 'water activities', 'swimming, breaststroke, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (18270, 11.0, 'water activities', 'swimming, butterfly, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (18280, 11.0, 'water activities', 'swimming, crawl, fast (75 yards/minute), vigorous effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18290, 8.0, 'water activities', 'swimming, crawl, slow (50 yards/minute), moderate or light effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18300, 6.0, 'water activities', 'swimming, lake, ocean, river (Taylor Codes 280, 295)');
--INSERT INTO activity (code, mets, heading, description) VALUES (18310, 6.0, 'water activities', 'swimming, leisurely, not lap swimming, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (18320, 8.0, 'water activities', 'swimming, sidestroke, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (18330, 8.0, 'water activities', 'swimming, synchronized');
--INSERT INTO activity (code, mets, heading, description) VALUES (18340, 10.0, 'water activities', 'swimming, treading water, fast vigorous effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (18350, 4.0, 'water activities', 'swimming, treading water, moderate effort, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (18355, 4.0, 'water activities', 'water aerobics, water calisthenics');
--INSERT INTO activity (code, mets, heading, description) VALUES (18360, 10.0, 'water activities', 'water polo');
--INSERT INTO activity (code, mets, heading, description) VALUES (18365, 3.0, 'water activities', 'water volleyball');
--INSERT INTO activity (code, mets, heading, description) VALUES (18366, 8.0, 'water activities', 'water jogging');
--INSERT INTO activity (code, mets, heading, description) VALUES (18370, 5.0, 'water activities', 'whitewater rafting, kayaking, or canoeing');
--INSERT INTO activity (code, mets, heading, description) VALUES (19010, 6.0, 'winter activities', 'moving ice house (set up/drill holes, etc.)');
--INSERT INTO activity (code, mets, heading, description) VALUES (19020, 5.5, 'winter activities', 'skating, ice, 9 mph or less');
--INSERT INTO activity (code, mets, heading, description) VALUES (19030, 7.0, 'winter activities', 'skating, ice, general (Taylor Code 360)');
--INSERT INTO activity (code, mets, heading, description) VALUES (19040, 9.0, 'winter activities', 'skating, ice, rapidly, more than 9 mph');
--INSERT INTO activity (code, mets, heading, description) VALUES (19050, 15.0, 'winter activities', 'skating, speed, competitive');
--INSERT INTO activity (code, mets, heading, description) VALUES (19060, 7.0, 'winter activities', 'ski jumping (climb up carrying skis)');
--INSERT INTO activity (code, mets, heading, description) VALUES (19075, 7.0, 'winter activities', 'skiing, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (19080, 7.0, 'winter activities', 'skiing, cross country, 2.5 mph, slow or light effort, ski walking');
--INSERT INTO activity (code, mets, heading, description) VALUES (19090, 8.0, 'winter activities', 'skiing, cross country, 4.0-4.9 mph, moderate speed and effort, genera');
--INSERT INTO activity (code, mets, heading, description) VALUES (19100, 9.0, 'winter activities', 'skiing, cross country, 5.0-7.9 mph, brisk speed, vigorous effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (19110, 14.0, 'winter activities', 'skiing, cross country, >8.0 mph, racing');
--INSERT INTO activity (code, mets, heading, description) VALUES (19130, 16.5, 'winter activities', 'skiing, cross country, hard snow, uphill, maximum, snow mountaineering');
--INSERT INTO activity (code, mets, heading, description) VALUES (19150, 5.0, 'winter activities', 'skiing, downhill, light effort');
--INSERT INTO activity (code, mets, heading, description) VALUES (19160, 6.0, 'winter activities', 'skiing, downhill, moderate effort, general');
--INSERT INTO activity (code, mets, heading, description) VALUES (19170, 8.0, 'winter activities', 'skiing, downhill, vigorous effort, racing');
--INSERT INTO activity (code, mets, heading, description) VALUES (19180, 7.0, 'winter activities', 'sledding, tobogganing, bobsledding, luge (Taylor Code 370)');
--INSERT INTO activity (code, mets, heading, description) VALUES (19190, 8.0, 'winter activities', 'snow shoeing');
--INSERT INTO activity (code, mets, heading, description) VALUES (19200, 3.5, 'winter activities', 'snowmobiling');
--INSERT INTO activity (code, mets, heading, description) VALUES (20000, 1.0, 'religious activities', 'sitting in church, in service, attending a ceremony, sitting quietly');
--INSERT INTO activity (code, mets, heading, description) VALUES (20001, 2.5, 'religious activities', 'sitting, playing an instrument at church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20005, 1.5, 'religious activities', 'sitting in church, talking or singing, attending a ceremony, sitting, active participation');
--INSERT INTO activity (code, mets, heading, description) VALUES (20010, 1.3, 'religious activities', 'sitting, reading religious materials at home');
--INSERT INTO activity (code, mets, heading, description) VALUES (20015, 1.2, 'religious activities', 'standing in church (quietly), attending a ceremony, standing quietly');
--INSERT INTO activity (code, mets, heading, description) VALUES (20020, 2.0, 'religious activities', 'standing, singing in church, attending a ceremony, standing, active participation');
--INSERT INTO activity (code, mets, heading, description) VALUES (20025, 1.0, 'religious activities', 'kneeling in church/at home (praying)');
--INSERT INTO activity (code, mets, heading, description) VALUES (20030, 1.8, 'religious activities', 'standing, talking in church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20035, 2.0, 'religious activities', 'walking in church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20036, 2.0, 'religious activities', 'walking, less than 2.0 mph - very slow');
--INSERT INTO activity (code, mets, heading, description) VALUES (20037, 3.3, 'religious activities', 'walking, 3.0 mph, moderate speed, not carrying anything');
--INSERT INTO activity (code, mets, heading, description) VALUES (20038, 3.8, 'religious activities', 'walking, 3.5 mph, brisk speed, not carrying anything');
--INSERT INTO activity (code, mets, heading, description) VALUES (20039, 2.0, 'religious activities', 'walk/stand combination for religious purposes, usher');
--INSERT INTO activity (code, mets, heading, description) VALUES (20040, 5.0, 'religious activities', 'praise with dance or run, spiritual dancing in church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20045, 2.5, 'religious activities', 'serving food at church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20046, 2.0, 'religious activities', 'preparing food at church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20047, 2.3, 'religious activities', 'washing dishes/cleaning kitchen at church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20050, 1.5, 'religious activities', 'eating at church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20055, 2.0, 'religious activities', 'eating/talking at church or standing eating, American Indian Feast days');
--INSERT INTO activity (code, mets, heading, description) VALUES (20060, 3.0, 'religious activities', 'cleaning church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20061, 5.0, 'religious activities', 'general yard work at church');
--INSERT INTO activity (code, mets, heading, description) VALUES (20065, 2.5, 'religious activities', 'standing - moderate (lifting 50 lbs., assembling at fast rate)');
--INSERT INTO activity (code, mets, heading, description) VALUES (20095, 4.0, 'religious activities', 'standing - moderate/heavy work');
--INSERT INTO activity (code, mets, heading, description) VALUES (20100, 1.5, 'religious activities', 'typing, electric, manual, or computer');
--INSERT INTO activity (code, mets, heading, description) VALUES (21000, 1.5, 'volunteer activities', 'sitting - meeting, general, and/or with talking involved');
--INSERT INTO activity (code, mets, heading, description) VALUES (21005, 1.5, 'volunteer activities', 'sitting - light office work, in general');
--INSERT INTO activity (code, mets, heading, description) VALUES (21010, 2.5, 'volunteer activities', 'sitting - moderate work');
--INSERT INTO activity (code, mets, heading, description) VALUES (21015, 2.3, 'volunteer activities', 'standing - light work (filing, talking, assembling)');
--INSERT INTO activity (code, mets, heading, description) VALUES (21016, 2.5, 'volunteer activities', 'sitting, child care, only active periods');
--INSERT INTO activity (code, mets, heading, description) VALUES (21017, 3.0, 'volunteer activities', 'standing, child care, only active periods');
--INSERT INTO activity (code, mets, heading, description) VALUES (21018, 4.0, 'volunteer activities', 'walk/run play with children, moderate, only active periods');
--INSERT INTO activity (code, mets, heading, description) VALUES (21019, 5.0, 'volunteer activities', 'walk/run play with children, vigorous, only active periods');
--INSERT INTO activity (code, mets, heading, description) VALUES (21020, 3.0, 'volunteer activities', 'standing - light/moderate work (pack boxes, assemble/repair, set up chairs/furniture)');
--INSERT INTO activity (code, mets, heading, description) VALUES (21025, 3.5, 'volunteer activities', 'standing - moderate (lifting 50 lbs., assembling at fast rate)');
--INSERT INTO activity (code, mets, heading, description) VALUES (21030, 4.0, 'volunteer activities', 'standing - moderate/heavy work');
--INSERT INTO activity (code, mets, heading, description) VALUES (21035, 1.5, 'volunteer activities', 'typing, electric, manual, or computer');
--INSERT INTO activity (code, mets, heading, description) VALUES (21040, 2.0, 'volunteer activities', 'walking, less than 2.0 mph, very slow');
--INSERT INTO activity (code, mets, heading, description) VALUES (21045, 3.3, 'volunteer activities', 'walking, 3.0 mph, moderate speed, not carrying anything');
--INSERT INTO activity (code, mets, heading, description) VALUES (21050, 3.8, 'volunteer activities', 'walking, 3.5 mph, brisk speed, not carrying anything');
--INSERT INTO activity (code, mets, heading, description) VALUES (21055, 3.0, 'volunteer activities', 'walking, 2.5 mph slowly and carrying objects less than 25 pounds');
--INSERT INTO activity (code, mets, heading, description) VALUES (21060, 4.0, 'volunteer activities', 'walking, 3.0 mph moderately and carrying objects less than 25 pounds, pushing something');
--INSERT INTO activity (code, mets, heading, description) VALUES (21065, 4.5, 'volunteer activities', 'walking, 3.5 mph, briskly and carrying objects less than 25 pounds');
--INSERT INTO activity (code, mets, heading, description) VALUES (21070, 3.0, 'volunteer activities', 'walk/stand combination, for volunteer purposes');
